// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	entity "BE_Friends_Management/internal/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockAuthRepository) CreateToken(token *entity.UserToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthRepositoryMockRecorder) CreateToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockAuthRepository)(nil).CreateToken), token)
}

// FindByRefreshToken mocks base method.
func (m *MockAuthRepository) FindByRefreshToken(refreshToken string) (*entity.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRefreshToken", refreshToken)
	ret0, _ := ret[0].(*entity.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRefreshToken indicates an expected call of FindByRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) FindByRefreshToken(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).FindByRefreshToken), refreshToken)
}

// SetRefreshTokenIsRevoked mocks base method.
func (m *MockAuthRepository) SetRefreshTokenIsRevoked(refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefreshTokenIsRevoked", refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefreshTokenIsRevoked indicates an expected call of SetRefreshTokenIsRevoked.
func (mr *MockAuthRepositoryMockRecorder) SetRefreshTokenIsRevoked(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefreshTokenIsRevoked", reflect.TypeOf((*MockAuthRepository)(nil).SetRefreshTokenIsRevoked), refreshToken)
}
