// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBlockRelationshipService is a mock of BlockRelationshipService interface.
type MockBlockRelationshipService struct {
	ctrl     *gomock.Controller
	recorder *MockBlockRelationshipServiceMockRecorder
}

// MockBlockRelationshipServiceMockRecorder is the mock recorder for MockBlockRelationshipService.
type MockBlockRelationshipServiceMockRecorder struct {
	mock *MockBlockRelationshipService
}

// NewMockBlockRelationshipService creates a new mock instance.
func NewMockBlockRelationshipService(ctrl *gomock.Controller) *MockBlockRelationshipService {
	mock := &MockBlockRelationshipService{ctrl: ctrl}
	mock.recorder = &MockBlockRelationshipServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockRelationshipService) EXPECT() *MockBlockRelationshipServiceMockRecorder {
	return m.recorder
}

// CreateBlockRelationship mocks base method.
func (m *MockBlockRelationshipService) CreateBlockRelationship(requestorEmail, targetEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlockRelationship", requestorEmail, targetEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlockRelationship indicates an expected call of CreateBlockRelationship.
func (mr *MockBlockRelationshipServiceMockRecorder) CreateBlockRelationship(requestorEmail, targetEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlockRelationship", reflect.TypeOf((*MockBlockRelationshipService)(nil).CreateBlockRelationship), requestorEmail, targetEmail)
}
